### ISSUE TITLE
Фильтр в marketplace (по стоимости)

### ISSUE THREAD

**Issue by orestx** [libertyads/marketplace#29]
![image](https://cloud.githubusercontent.com/assets/2162824/6597181/5f055c88-c803-11e4-8d78-4dc356a693ad.png)

В режиме рекламодателя, нужно что бы фильтр по стоимости работал наоборот, тоесть что бы можно было увидеть предложения с суммой меньше указанной мной планки.

**Comment by orestx** [comment]
гуд

**Comment by orestx** [comment]
![image](https://cloud.githubusercontent.com/assets/2162824/6916121/41842ac8-d7a2-11e4-863e-3d10418e12fa.png)

Еще поправка. Когда я в режиме Publisher, уровень моего заработка зависит от того, сколько у меня читателей, количество которых у меня ограничено. Поэтому тут я бы поставил фильтр тоже в обратном направлении. Что бы я мог смотреть предложения, которые "могу потянуть".

**Comment by maximsheiko** [comment]
Сделал,но сразу много вопросов появилось : 
какое начальное значение устанавливать для фильтра?
что будет если заказчик установит количество выше 10к - они просто не будут отображаться

**Comment by orestx** [comment]
>что будет если заказчик установит количество выше 10к

На этот случай есть параметр "All"

**Comment by maximsheiko** [comment]
>есть параметр "All"
в данный момент нет. я сделаю

**Comment by orestx** [comment]
ок
