### ISSUE TITLE
Add google & mixpanel analytics  

### ISSUE THREAD

**Issue by alexzaporozhets** [libertyads/marketplace#4]
https://github.com/okgrow/analytics/

**Comment by alexzaporozhets** [comment]
Mixpanel token: d4a5374551c3107ce90916230ef7bc93

**Comment by alexzaporozhets** [comment]
@orestx какоу key для google?

**Comment by orestx** [comment]
google-analytics (старый, от libertyads): UA-45733566-7

**Comment by alexzaporozhets** [comment]
@bezrukkolyaisells добавь аналитику пользователей + events

**Comment by orestx** [comment]
google-analytics работает

**Comment by orestx** [comment]
В mixpanel у нас нет свойства "Created" (дата регистрации), но оно нужно нам... Это на стороне нашего сайта настраивается? Нужно добавить.

**Comment by bezrukkolyaisells** [comment]
@maximsheiko: нужно добавить свойство created: user.createdAt в
https://github.com/libertyads/marketplace/blob/master/client/startup.js#L38-L40

**Comment by orestx** [comment]
Вопрос с Created обсуждается еще тут: https://github.com/libertyads/marketplace/issues/47

Поэтому эту тему закрываю.
