### ISSUE TITLE
письмо на следующий день после регистрации через mixpanel

### ISSUE THREAD

**Issue by orestx** [libertyads/marketplace#47]
Нужно что бы у нас после регистрации пользователя отправлялось письмо через mixpanel (настроить правило рассылки). Сейчас там, в mixpanel, не хватает свойства "created", поэтому откладываю эту задачу.. Приблизительный вид письма:

Hey {{ usrname }},

I noticed that you just signed up for libertyads.me.
I'm here to help. Please don't hesitate to let me know if you have any questions about the tool, if you're having trouble connecting social accounts.

{{ManagerName}}
LibertyAds team

**Comment by orestx** [comment]
@maximsheiko, тебе нужно сделать что бы у нас в mixpanel появилась опция Created (такое есть, например на msp4me). Как это сделаешь, переведешь задачу на меня.

**Comment by maximsheiko** [comment]
по идее сделал

**Comment by orestx** [comment]
в опциях не появилось, но я еще посмотрю, может нужно в личном кабинете mixpanel что то еще сделать

**Comment by maximsheiko** [comment]
исправил

**Comment by orestx** [comment]
Поле появилось, а вот данных в графе Created нет (2 min ago это Last seen,  а на месте Created - пусто):
![image](https://cloud.githubusercontent.com/assets/2162824/7560663/efdca730-f7cd-11e4-9e0a-df14de63294f.png)

Данные Created есть только у этой регистрации: 
![image](https://cloud.githubusercontent.com/assets/2162824/7560705/4392dcc8-f7ce-11e4-9d5a-d912ea3cfbf3.png)

**Comment by maximsheiko** [comment]
потому что я создал эту регистрацию после исправления,все старые будут без Created
так если графа появляется - в чем проблема тогда?

**Comment by orestx** [comment]
Проблема в том что это **новая** учетка была без данных. Но сейчас они появились. Похоже что mixpanel не сразу выдает актуальные данные. В общем ок, информация подтянулась
![image](https://cloud.githubusercontent.com/assets/2162824/7561907/985267f6-f7d8-11e4-930b-2b60a575d0e7.png)

**Comment by orestx** [comment]
Активировал, на днях увидим как работает.
