### ISSUE TITLE
У нас контент страницы очень сильно налазит на меню. Нужно расстояние какое то нормальное сделать

### ISSUE THREAD

**Issue by orestx** [libertyads/marketplace#52]
![image](https://cloud.githubusercontent.com/assets/2162824/7491065/78249492-f3ee-11e4-96bd-09e928a5061e.png)
Пикселей так 25, а там посмотрим...
Это касается всех страниц, должно быть стандартное расстояние.

**Comment by alexzaporozhets** [comment]
@annagordienko7 проверь, мне кажется это появилось после обновления дизайна стартовой

**Comment by orestx** [comment]
норм
